# Generated by Django 5.0.14 on 2026-07-15 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_author_id_alter_post_id_alter_tag_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagen_portada',
            field=models.ImageField(blank=True, null=True, upload_to='portadas/'),
        ),
    ]
